export const CATEGORIES: Record<string, string> = {
  pupil: 'Учащиеся',
  student: 'Студенты',
  other_education: 'Прочие обучающиеся',
  social: 'Социальные льготники',
  other: 'Остальные',
  unknown: 'Неизвестно',
};

export const POI_KINDS: Record<string, string> = {
  hospital: 'Больницы',
  clinic_adult: 'Взрослые поликлиники',
  clinic_child: 'Детские поликлиники',
  clinic_unspecified: 'Поликлиники',
  diagnostic: 'Диагностика',
  healthcare_other: 'Другие медучреждения',
  pharmacy: 'Аптеки',
  metro_station: 'Станции метро',
  metro_entrance: 'Входы метро',
  rail_station: 'Железнодорожные станции',
  rail_entrance: 'Входы железнодорожных станций',
  bus_station: 'Автостанции',
  transit_hub: 'Пересадочные узлы',
  school: 'Школы',
  college: 'Колледжи',
  university: 'Вузы',
  kindergarten: 'Детские сады',
  dormitory: 'Общежития',
  office: 'Офисы',
  factory: 'Производства',
  mfc: 'МФЦ',
  social: 'Социальные учреждения',
  mall: 'Торговые центры',
  market: 'Рынки',
  supermarket: 'Супермаркеты',
  park: 'Парки',
  stadium: 'Стадионы',
  sports_centre: 'Спортивные центры',
  museum: 'Музеи',
  theatre: 'Театры',
  concert: 'Концертные залы',
  culture: 'Культурные объекты',
  residential: 'Жилые объекты',
  mcc_stations: 'Станции МЦК',
  mcd_stations: 'Станции МЦД',
  residents: 'Население · оценка',
  population: 'Население · оценка',
};

export const STATUS: Record<string, string> = {
  spring_to_summer: 'Апрель–май → лето',
  august_to_autumn: 'Август → осень',
  continued_from_summer: 'Продолжили после лета',
  returned_after_summer_absence: 'Вернулись после отсутствия летом',
  previous_attempts_without_prior_success: 'Ранее были только отказы',
  first_observed_autumn: 'Впервые замечены осенью',
};
