CATEGORIES = {
    "pupil": "Учащиеся",
    "student": "Студенты",
    "other_education": "Прочие обучающиеся",
    "social": "Социальные льготники",
    "other": "Остальные",
    "unknown": "Неизвестно",
}

TABLES = (
    "route_hour_total",
    "route_hour_category",
    "fare_dictionary",
    "category_summary",
    "category_daily_complete",
    "category_month_profiles",
    "category_dow_profiles",
    "category_hour_profiles",
    "category_month_dow_hour",
    "seasonal_contributions",
    "seasonal_contributions_by_route",
    "seasonal_sensitivity_time",
    "seasonal_sensitivity_work_calendar",
    "fixed_cohort_summary",
    "cohort_category_changes",
    "autumn_return_summary",
    "autumn_return_total",
    "category_switch_summary",
    "route_infrastructure_monthly",
    "stop_infrastructure_monthly",
    "infrastructure_demand_associations",
    "route_infrastructure_demand_diagnostic",
    "forecast_summary",
    "forecast_metrics",
    "forecast_bootstrap",
    "boarding_pilot_summary",
)

KEYS = {
    "route_hour_total": ["route", "date", "hour"],
    "route_hour_category": ["route", "date", "hour", "category"],
    "fare_dictionary": ["raw_name"],
    "route_infrastructure_monthly": ["snapshot", "route"],
    "stop_infrastructure_monthly": ["snapshot", "route", "stop_occurrence_id"],
    "fixed_cohort_summary": ["cohort_category", "period_start"],
    "category_summary": ["category"],
    "category_daily_complete": ["date", "category"],
    "category_month_profiles": ["category", "month"],
    "category_dow_profiles": ["category", "dow"],
    "category_hour_profiles": ["category", "hour"],
    "category_month_dow_hour": ["category", "month", "dow", "hour"],
    "seasonal_contributions": ["category", "comparison"],
    "seasonal_contributions_by_route": ["route", "category", "comparison"],
    "seasonal_sensitivity_time": ["category", "comparison", "time_window", "day_type"],
    "seasonal_sensitivity_work_calendar": ["category", "comparison", "time_window", "day_type"],
    "cohort_category_changes": ["cohort_category", "observed_category", "month"],
    "autumn_return_summary": ["autumn_status", "in_spring_cohort", "category"],
    "autumn_return_total": ["autumn_status", "in_spring_cohort"],
    "category_switch_summary": ["month", "prior_category", "category"],
    "infrastructure_demand_associations": ["snapshot", "category", "radius_m"],
    "route_infrastructure_demand_diagnostic": ["snapshot", "route"],
    "forecast_summary": ["model"],
    "forecast_metrics": ["origin", "model", "slice"],
    "forecast_bootstrap": ["model"],
    "boarding_pilot_summary": ["window_minutes"],
}

NOTES = [
    "Категории описывают билеты; карта не равна человеку, возраст не определён.",
    "Уникальные карты нельзя складывать между часами, маршрутами и категориями.",
    "Инфраструктура описывает окружение, а не цель поездки. Расстояние — по прямой.",
    "Остановки посадки не установлены; категориального прогноза нет.",
    "Когорты и сезонные сравнения имеют фиксированные исследовательские периоды.",
]
